In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import sys

x = torch.rand((1,1,25,8))
conv1 = nn.Conv2d(1, 8, (5, 3), bias=False)
conv2 = nn.Conv2d(8, 4, (5, 3), bias=False)
#conv3 = nn.Conv2d(16, 32, (5, 3), bias=False)
fc1 = nn.Linear(4 * 17 * 4, 32, bias=False)
fc2 = nn.Linear(32, 4 * 17 *4, bias=False) 
#deconv1 = nn.ConvTranspose2d(32, 16, (5, 3), bias=False)
deconv2 = nn.ConvTranspose2d(4, 8, (5, 3), bias=False)
deconv3 = nn.ConvTranspose2d(8, 1, (5, 3), bias=False)
bn1 = nn.BatchNorm2d(8, eps=1e-04, affine=False)
bn2 = nn.BatchNorm2d(4, eps=1e-04, affine=False)
bn3 = nn.BatchNorm2d(8, eps=1e-04, affine=False)
bn4 = nn.BatchNorm2d(4, eps=1e-04, affine=False)
bn5 = nn.BatchNorm2d(8, eps=1e-04, affine=False)


x = conv1(x)
x = F.leaky_relu(bn1(x))
print(x.shape)
x = conv2(x)
x = F.leaky_relu(bn2(x))
print(x.shape)
print(x.size(0))
x = x.view(x.size(0), -1)
x = fc1(x)
#x = conv3(x)
#x = F.leaky_relu(bn3(x))
#print(x.shape)
#x = deconv1(x)
#x = F.leaky_relu(bn4(x))
#print(x.shape)
x = fc2(x)
print(x.shape)
x = x.view(x.size(0), 4, 17, 4)
print(x.shape)
x = deconv2(x)
x = F.leaky_relu(bn3(x))
print(x.shape)
x = deconv3(x)
print(x.shape)





torch.Size([1, 8, 21, 6])
torch.Size([1, 4, 17, 4])
1
torch.Size([1, 272])
torch.Size([1, 4, 17, 4])
torch.Size([1, 8, 21, 6])
torch.Size([1, 1, 25, 8])


In [22]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import sys

x = torch.rand((1,1,25,8))

r = nn.ReLU()
l1 = nn.Linear(25 * 8, 64)
l2 = nn.Linear(64, 32)
l3 = nn.Linear(32, 64)
l4 = nn.Linear(64, 25 * 8)

x = x.view(x.size(0), -1)
print(x.shape)
x = l1(x)
print(x.shape)
x = r(x)
print(x.shape)
x = l2(x)
print(x.shape)
x = r(x)
print(x.shape)
x = l3(x)
print(x.shape)
x = r(x)
print(x.shape)
x = l4(x)
print(x.shape)
x = r(x)
print(x.shape)
x = x.view(x.size(0), 1, 25, 8)
print(x.shape)


torch.Size([1, 200])
torch.Size([1, 64])
torch.Size([1, 64])
torch.Size([1, 32])
torch.Size([1, 32])
torch.Size([1, 64])
torch.Size([1, 64])
torch.Size([1, 200])
torch.Size([1, 200])
torch.Size([1, 1, 25, 8])


In [39]:
import numpy as np
my_data = np.load('/home/vimlab/workspace/source/PyTorch-Deep-SVDD/data/NTU/ntu_skeleton_feature.npy')
my_data = my_data[:,:,0:3]
print(my_data.shape)
print(my_data[0].shape)
#print(my_data[0])

moving_point = my_data[1][0]
print(moving_point)
for i in range(25):
    print(my_data[1][i]-moving_point)


# def normalize_joint_coordinates(data):

#     n, j, _ = data.shape
#     for i in range(n):
#         moving_point = data[0]
#         for k in range(j):



(5583988, 25, 3)
(25, 3)
[0.4444558  0.05479737 3.57294   ]
[0. 0. 0.]
[-1.6270000e-04  2.9607103e-01 -2.4220000e-03]
[-0.0024191   0.58584423 -0.017996  ]
[ 0.0236965   0.70612743 -0.011611  ]
[-0.1027518   0.46246813 -0.133952  ]
[-0.1710374   0.21617593 -0.180318  ]
[-0.181603    0.00223845 -0.230559  ]
[-0.184845   -0.03776962 -0.234286  ]
[0.101496   0.46086843 0.022315  ]
[0.1288878  0.21128823 0.05692   ]
[ 0.1311071  -0.02850716  0.061787  ]
[ 0.1226211  -0.07609518  0.077901  ]
[-0.0499064   0.00275837 -0.068529  ]
[-0.1114496  -0.29816257 -0.090842  ]
[-0.1421379  -0.62512567 -0.046491  ]
[-0.1183107  -0.67890907 -0.076339  ]
[ 0.0408244 -0.0045337 -0.003349 ]
[-0.0086999  -0.29745537  0.004447  ]
[-0.0638813  -0.61934737  0.043875  ]
[-0.0393935  -0.67289387  0.00871   ]
[-0.0015455   0.51429853 -0.011772  ]
[-0.1870992  -0.09917225 -0.233152  ]
[-0.1545815  -0.05198419 -0.220384  ]
[ 0.1170352  -0.13266193  0.099379  ]
[ 0.1032143  -0.09199058  0.04886   ]


In [1]:
import numpy as np
my_data = np.load('/home/vimlab/workspace/source/PyTorch-Deep-SVDD/data/NTU/ntu_skeleton_feature.npy')
my_data = my_data[:,:,0:3]
print(my_data.shape)
print(my_data[0].shape)
#print(my_data[0])

moving_point = my_data[1][0]
print(moving_point)
for i in range(25):
    print(my_data[1][i]-moving_point)

(5583988, 25, 3)
(25, 3)
[0.4442474 0.054712  3.57226  ]
[0. 0. 0.]
[-0.0028485  0.2957536 -0.006999 ]
[-0.0099842  0.5848849 -0.030055 ]
[ 0.0234223  0.7058644 -0.014124 ]
[-0.1054737  0.4631597 -0.137984 ]
[-0.1722978  0.2161725 -0.18178  ]
[-0.1795962   0.00458567 -0.232241  ]
[-0.1690526  -0.04177333 -0.225016  ]
[0.0940839 0.4590389 0.010354 ]
[0.1215388 0.2094954 0.045097 ]
[ 0.1210065  -0.02941541  0.051527  ]
[ 0.1184367  -0.07142435  0.070447  ]
[-0.0498677   0.00286404 -0.06818   ]
[-0.1169443 -0.2978638 -0.088864 ]
[-0.1416032 -0.6247373 -0.044441 ]
[-0.1182599 -0.6788275 -0.075572 ]
[ 0.040842   -0.00458837 -0.003689  ]
[-0.0097486 -0.2980684  0.004469 ]
[-0.0635423 -0.6190805  0.044873 ]
[-0.0387976 -0.6738308  0.011662 ]
[-0.0077229  0.5135517 -0.021756 ]
[-0.1768409  -0.10610767 -0.220892  ]
[-0.1199589  -0.04929545 -0.21441   ]
[ 0.1079957 -0.1258486  0.093002 ]
[ 0.1024718  -0.08883885  0.044558  ]


In [40]:
import numpy as np
my_data = np.load('/home/vimlab/workspace/source/PyTorch-Deep-SVDD/data/NTU/ntu_skeleton_feature.npy')
my_data = my_data[:,:,0:3]
print(my_data.shape)
print(my_data[0].shape)
print(my_data[0])

(5583988, 25, 3)
(25, 3)
[[ 4.444558e-01  5.479737e-02  3.572940e+00]
 [ 4.442931e-01  3.508684e-01  3.570518e+00]
 [ 4.420367e-01  6.406416e-01  3.554944e+00]
 [ 4.681523e-01  7.609248e-01  3.561329e+00]
 [ 3.417040e-01  5.172655e-01  3.438988e+00]
 [ 2.734184e-01  2.709733e-01  3.392622e+00]
 [ 2.628528e-01  5.703582e-02  3.342381e+00]
 [ 2.596108e-01  1.702775e-02  3.338654e+00]
 [ 5.459518e-01  5.156658e-01  3.595255e+00]
 [ 5.733436e-01  2.660856e-01  3.629860e+00]
 [ 5.755629e-01  2.629021e-02  3.634727e+00]
 [ 5.670769e-01 -2.129781e-02  3.650841e+00]
 [ 3.945494e-01  5.755574e-02  3.504411e+00]
 [ 3.330062e-01 -2.433652e-01  3.482098e+00]
 [ 3.023179e-01 -5.703283e-01  3.526449e+00]
 [ 3.261451e-01 -6.241117e-01  3.496601e+00]
 [ 4.852802e-01  5.026367e-02  3.569591e+00]
 [ 4.357559e-01 -2.426580e-01  3.577387e+00]
 [ 3.805745e-01 -5.645500e-01  3.616815e+00]
 [ 4.050623e-01 -6.180965e-01  3.581650e+00]
 [ 4.429103e-01  5.690959e-01  3.561168e+00]
 [ 2.573566e-01 -4.437488e-02 

: 

In [31]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[10,9,8,7,6,5,4,3,2,1]])
print(torch.mean(a, dim=0))


tensor([5.5000, 5.5000, 5.5000, 5.5000, 5.5000, 5.5000, 5.5000, 5.5000, 5.5000,
        5.5000])


In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class skel_convautoencoder(nn.Module):
    def __init__(self):
        super(skel_convautoencoder, self).__init__()

        self.conv1 = nn.Conv2d(1, 8, 3, bias=False)
        self.bn1 = nn.BatchNorm2d(8, eps=1e-04, affine=False)
        self.conv2 = nn.Conv2d(8, 16, 3, bias=False)
        self.bn2 = nn.BatchNorm2d(4, eps=1e-04, affine=False)
        self.conv3 = nn.Conv2d(16, 32, 3, bias=False)
        self.bn3 = nn.BatchNorm2d(32, eps=1e-04, affine=False)

        # self.fc1 = nn.Linear(4 * 17 * 4, 32, bias=False)
        # self.fc2 = nn.Linear(32, 4 * 17 *4, bias=False) 

        self.deconv1 = nn.ConvTranspose2d(32, 16, 3, bias=False)
        self.bn3 = nn.BatchNorm2d(16, eps=1e-04, affine=False)
        self.deconv2 = nn.ConvTranspose2d(16, 8, 3, bias=False)
        self.bn4 = nn.BatchNorm2d(8, eps=1e-04, affine=False)
        self.deconv3 = nn.ConvTranspose2d(8, 1, 3, bias=False)

model = skel_convautoencoder()
print(model)

skel_convautoencoder(
  (conv1): Conv2d(1, 8, kernel_size=(3, 3), stride=(1, 1), bias=False)
  (bn1): BatchNorm2d(8, eps=0.0001, momentum=0.1, affine=False, track_running_stats=True)
  (conv2): Conv2d(8, 16, kernel_size=(3, 3), stride=(1, 1), bias=False)
  (bn2): BatchNorm2d(4, eps=0.0001, momentum=0.1, affine=False, track_running_stats=True)
  (conv3): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), bias=False)
  (bn3): BatchNorm2d(16, eps=0.0001, momentum=0.1, affine=False, track_running_stats=True)
  (deconv1): ConvTranspose2d(32, 16, kernel_size=(3, 3), stride=(1, 1), bias=False)
  (deconv2): ConvTranspose2d(16, 8, kernel_size=(3, 3), stride=(1, 1), bias=False)
  (bn4): BatchNorm2d(8, eps=0.0001, momentum=0.1, affine=False, track_running_stats=True)
  (deconv3): ConvTranspose2d(8, 1, kernel_size=(3, 3), stride=(1, 1), bias=False)
)


In [6]:
import numpy as np
import torch

a = torch.zeros(6)
a[:3] = 1
print(a)

tensor([1., 1., 1., 0., 0., 0.])


In [4]:
import numpy as np
my_data = np.load('/home/vimlab/workspace/source/PyTorch-Deep-SVDD_real/data/NTU/Our_ntu_skeleton_data_with_synthetic.npz')

train = my_data['train']
test = my_data['test']

x = train[:,:,0]
print(x.flatten().mean())




-0.006065683842671319


In [11]:
a = np.arange(6)
b = np.arange(6)
c = np.arange(6)

d = [[0, 1, 2], [3, 4, 5]]

a = a.reshape(-1,3,1)
b = b.reshape(-1,3,1)
c = c.reshape(-1,3,1)


print(np.concatenate([a, b, c], axis=2))



[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]
  [5 5 5]]]


In [53]:
import pickle
import numpy as np
from tqdm import tqdm
with open('/home/vimlab/workspace/source/PyTorch-Deep-SVDD_real/data/NTU/raw_denoised_joints.pkl', 'rb') as fr:
    raw_skes_data = pickle.load(fr)

one_denoised_poses_list = []
two_denoised_poses_list = []

for (idx, body_data) in enumerate(tqdm(raw_skes_data)):
    if body_data.shape[1]==75:
        one_denoised_poses_list.append(body_data)
    elif body_data.shape[1]==150:
        two_denoised_poses_list.append(body_data)

one_denoised_poses = np.concatenate(one_denoised_poses_list, axis=0)
two_denoised_poses = np.concatenate(two_denoised_poses_list, axis=0)

np.save('my_one_denoised_poses.npy', one_denoised_poses)
np.save('my_two_denoised_poses.npy', two_denoised_poses)
print(one_denoised_poses.shape)        
print(two_denoised_poses.shape)

100%|██████████| 56578/56578 [00:00<00:00, 2797686.12it/s]


(4030455, 75)
(742115, 150)


In [73]:
import numpy as np
np.set_printoptions(linewidth=np.inf)
data = np.load('/home/vimlab/workspace/source/visualization/my_visualization/Our_ntu_denoised_skeleton_data_with_synthetic.npz')
train = data['train']
test = data['test']
synthetic_test = data['synthetic_test']
train = train.reshape(-1, 25, 3)
test = test.reshape(-1, 25, 3)
synthetic_test = synthetic_test.reshape(-1, 25, 3)
#data = data.reshape(-1, 50, 3)


for i in range(train.shape[0]):
    first_joint0 = train[i][0]
    #second_joint0 = data[i][25]
    #average_joint = (first_joint0 + second_joint0)/2
    #data[i] = data[i]-average_joint
    train[i] = train[i]-first_joint0

for i in range(test.shape[0]):
    first_joint0 = test[i][0]
    #second_joint0 = data[i][25]
    #average_joint = (first_joint0 + second_joint0)/2
    #data[i] = data[i]-average_joint
    test[i] = test[i]-first_joint0

for i in range(synthetic_test.shape[0]):
    first_joint0 = synthetic_test[i][0]
    #second_joint0 = data[i][25]
    #average_joint = (first_joint0 + second_joint0)/2
    #data[i] = data[i]-average_joint
    synthetic_test[i] = synthetic_test[i]-first_joint0

train = train.reshape(-1, 75)
test = test.reshape(-1, 75)
synthetic_test = synthetic_test.reshape(-1, 75)

print(synthetic_test[0])


# #np.save('my_one_denoised_centered_poses.npy', data)
#np.save('my_two_denoised_centered_poses.npy', data)
#np.savez('my_one_denoised_synthetic_centered_poses.npz', train=train, test=test, synthetic_test=synthetic_test)
# my_data = data[0]
# print(my_data.shape)
# joint0 = my_data[0]
# joint1 = my_data[25]
# print(joint0)
# print(joint1)
# #print(my_data)
# print(my_data[:3])
# print(my_data[25:28])
# my_data[:25] = my_data[:25]-joint0
# my_data[25:] = my_data[25:]-joint1

# print(my_data[:3])
# print(my_data[25:28])


[ 0.          0.          0.         -0.0161279   0.17958173 -0.13632298 -0.0323379   0.35845694 -0.2802379  -0.0030379   0.48322934 -0.32446194 -0.15151297  0.28142804 -0.28007293 -0.2911984  -0.30976146 -1.340353   -0.1258459  -0.44805717 -2.7211397  -0.10238475 -0.13706458 -2.8649638   0.11382578  0.3112828  -0.17420697  0.16706531  0.13125643 -0.07483101  0.2115664  -0.02995368 -0.17348003  0.21773    -0.07914409 -0.218786   -0.06454638 -0.00565031 -0.04546189 -0.06183901 -0.22327967 -0.3589189  -0.03093021 -0.5375606  -0.29166198 -0.0168927  -0.62086636 -0.34014392  0.06206609  0.00462481 -0.0116179   0.28864872 -0.10676886 -0.21844506  0.28387338 -0.42491367 -0.09301901  0.315659   -0.50412303 -0.17950296 -0.0282913   0.31392792 -0.24269891 -0.08914915 -0.2067696  -1.9304156  -0.16959101 -0.03512414 -1.7914183   0.2366821  -0.12631857 -0.25758004  0.18226211 -0.0781848  -0.20749998]


In [74]:
import numpy as np
np.set_printoptions(linewidth=np.inf)
la = np.load('/home/vimlab/workspace/source/visualization/my_visualization/synthetic/left_arm/synthetic_left_arm.npy')
ra = np.load('/home/vimlab/workspace/source/visualization/my_visualization/synthetic/right_arm/synthetic_right_arm.npy')
legs = np.load('/home/vimlab/workspace/source/visualization/my_visualization/synthetic/legs/synthetic_legs.npy')
bodys = np.load('/home/vimlab/workspace/source/visualization/my_visualization/synthetic/body/synthetic_bodies.npy')

la=la.reshape(1000, 25, 3)
ra=ra.reshape(1000, 25, 3)
legs=legs.reshape(1000, 25, 3)
bodys=bodys.reshape(1000, 25, 3)

for i in range(la.shape[0]):
    first_joint0 = la[i][0]
    #second_joint0 = data[i][25]
    #average_joint = (first_joint0 + second_joint0)/2
    #data[i] = data[i]-average_joint
    la[i] = la[i]-first_joint0

for i in range(ra.shape[0]):
    first_joint0 = ra[i][0]
    #second_joint0 = data[i][25]
    #average_joint = (first_joint0 + second_joint0)/2
    #data[i] = data[i]-average_joint
    ra[i] = ra[i]-first_joint0

for i in range(bodys.shape[0]):
    first_joint0 = bodys[i][0]
    #second_joint0 = data[i][25]
    #average_joint = (first_joint0 + second_joint0)/2
    #data[i] = data[i]-average_joint
    bodys[i] = bodys[i]-first_joint0

for i in range(legs.shape[0]):
    first_joint0 = legs[i][0]
    #second_joint0 = data[i][25]
    #average_joint = (first_joint0 + second_joint0)/2
    #data[i] = data[i]-average_joint
    legs[i] = legs[i]-first_joint0

la = la.reshape(1000,75)
ra = ra.reshape(1000,75)
legs = legs.reshape(1000,75)
bodys = bodys.reshape(1000,75)

np.save('./synthetic/body/synthetic_centered_bodies.npy', bodys)
np.save('./synthetic/left_arm/synthetic_centered_left_arm.npy', la)
np.save('./synthetic/right_arm/synthetic_centered_right_arm.npy', ra)
np.save('./synthetic/legs/synthetic_centered_legs.npy', legs)


In [50]:
import numpy as np
np.set_printoptions(linewidth=np.inf)
data = np.load('/home/vimlab/workspace/source/CTR-GCN/data/ntu/NTU60_CS.npz')
print(data['x_train'][0])

[[-0.0142139  -0.2600664   0.07078004 ...  0.          0.          0.        ]
 [-0.0138849  -0.2589618   0.07446694 ...  0.          0.          0.        ]
 [-0.01410781 -0.2588182   0.07586813 ...  0.          0.          0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.          0.        ]
 [ 0.          0.          0.         ...  0.          0.          0.        ]
 [ 0.          0.          0.         ...  0.          0.          0.        ]]


In [89]:
import numpy as np
np.set_printoptions(linewidth=np.inf)
data = np.load('/home/vimlab/workspace/source/PyTorch-Deep-SVDD_real/data/NTU/denoised_centered_poses.npy')

def return_min_max(arr):
    min = np.min(arr)
    max = np.max(arr)
    return min, max

my_data = data[0]
print(my_data.shape)
#print(my_data)
x = my_data[:,0]
y = my_data[:,1]
z = my_data[:,2]

min_x, max_x = return_min_max(x)
min_y, max_y = return_min_max(y)
min_z, max_z = return_min_max(z)




# for i in range(data.shape[0]):
#     x = data[i][:][0]
#     y = data[i][:][1]
#     z = data[i][:][2]
    



(25, 3)


In [ ]:
import pickle
import numpy as np
from tqdm import tqdm
with open('/home/vimlab/workspace/source/PyTorch-Deep-SVDD_real/data/NTU/raw_denoised_joints.pkl', 'rb') as fr:
    raw_skes_data = pickle.load(fr)

one_denoised_poses_list = []
two_denoised_poses_list = []

for (idx, body_data) in enumerate(tqdm(raw_skes_data)):
    if body_data.shape[1]==75:
        one_denoised_poses_list.append(body_data)
    elif body_data.shape[1]==150:
        two_denoised_poses_list.append(body_data)

one_denoised_poses = np.concatenate(one_denoised_poses_list, axis=0)
two_denoised_poses = np.concatenate(two_denoised_poses_list, axis=0)

np.save('my_one_denoised_poses.npy', one_denoised_poses)
np.save('my_two_denoised_poses.npy', two_denoised_poses)
print(one_denoised_poses.shape)        
print(two_denoised_poses.shape)

100%|██████████| 56578/56578 [00:00<00:00, 2797686.12it/s]


(4030455, 75)
(742115, 150)


In [100]:
import numpy as np

a = np.arange(50).reshape(1, 50)
print(a)
a = a.reshape(2, 25)

print(a[0])
print(a[1])

#print(a[0][:25].shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
